aws_region         = "us-east-1"
environment        = "Production"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
instance_type      = "t3.micro"
bucket_name        = "session19-production-cloud-assets-2026"
